version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam

  settings:
    errcheck:
      check-type-assertions: true
    govet:
      check-shadowing: true

formatters:
  enable:
    - gofmt
    - goimports
