options:
  healthchecks_dir: /home/niar/repos/sznuper/monorepo/healthchecks/build
  cache_dir: /home/niar/.cache/sznuper

globals:
  hostname: vps-01

services:
  telegram:
    url: telegram://${TELEGRAM_TOKEN}@telegram
    params:
      chats: ${TELEGRAM_CHAT_ID}

alerts:
  - name: disk_check_https
    healthcheck: https://github.com/sznuper/healthchecks/releases/download/v0.1.0/disk_usage
    sha256: 336d1a978140eb8d63d4f9699b5b7484a6f474f2eb8df2e19da3ba925de6ae4e
    trigger:
      interval: 2s
    timeout: 10s
    cooldown: 8s
    args:
      threshold_warn_percent: 2
      threshold_crit_percent: 90
    template: |-
      [{{event.type | upper}}] {{globals.hostname}}:
      Disk at {{event.usage_percent}}%
    notify:
      - telegram
    events:
      healthy: [ok]
