alerts:
  - name: sznuper_lifecycle
    healthcheck: builtin://lifecycle
    triggers:
      - lifecycle: true
    template: |-
      [{{event.type | upper}}] {{globals.hostname}}: sznuper {{event.type}}
