services:
  logger:
    url: logger://

alerts:
  - name: sznuper_lifecycle
    healthcheck: builtin://lifecycle
    trigger:
      lifecycle: true
    template: |-
      [{{event.type | upper}}] {{globals.hostname}}: sznuper {{event.type}}
    notify:
      - logger

  - name: disk_usage
    healthcheck: https://github.com/sznuper/healthchecks/releases/download/v0.9.0/disk_usage
    sha256: 336d1a978140eb8d63d4f9699b5b7484a6f474f2eb8df2e19da3ba925de6ae4e
    trigger:
      interval: 30s
    args:
      threshold_warn_percent: 80
      threshold_crit_percent: 95
      mount: /
    cooldown: 10m
    template: |-
      [{{event.type | upper}}] {{globals.hostname}}:
      Disk {{args.mount}} at {{event.usage_percent}}% ({{event.available}} remaining)
    notify:
      - logger
    events:
      healthy: [ok]

  - name: memory_usage
    healthcheck: https://github.com/sznuper/healthchecks/releases/download/v0.9.0/memory_usage
    sha256: 49b7985178bcbad1986aae9d703e982ca692a49206f4f906a80fadbf840811d6
    trigger:
      interval: 30s
    args:
      threshold_warn_percent: 80
      threshold_crit_percent: 95
    cooldown: 10m
    template: |-
      [{{event.type | upper}}] {{globals.hostname}}:
      Memory at {{event.usage_percent}}% ({{event.available}} remaining)
    notify:
      - logger
    events:
      healthy: [ok]

  - name: cpu_usage
    healthcheck: https://github.com/sznuper/healthchecks/releases/download/v0.9.0/cpu_usage
    sha256: 516160b6b69054642b67a816c229417c42acd5a1f0579c95421fb94d63f8d99a
    trigger:
      interval: 30s
    args:
      threshold_warn_percent: 80
      threshold_crit_percent: 95
    cooldown: 10m
    template: |-
      [{{event.type | upper}}] {{globals.hostname}}:
      CPU at {{event.usage_percent}}%
    notify:
      - logger
    events:
      healthy: [ok]
